### ISSUE TITLE
Calendar widget takes too much time to update highlighting

### ISSUE THREAD

**Issue by leonidasv** [elementary/os#128]
![](https://i.imgur.com/zfpAGNV.jpg)

After using the system for some days (with some suspends in between), I noticed the calendar does not update the day (in blue) immediately. The screenshot above shows, the current day is 19th but the calendar is still highlighting  17th. It randomly solves after closing and opening the widget multiple times or browsing through the months.

**Comment by peteruithoven** [comment]
This would be the appropriate repo for this issue: https://github.com/elementary/wingpanel-indicator-datetime
The System Settings > About > Report a Problem button can help you find the right repo. 

This should have been fixed with: https://github.com/elementary/wingpanel-indicator-datetime/pull/97
Which should have been released: https://github.com/elementary/wingpanel-indicator-datetime/releases/tag/2.1.2
