### ISSUE TITLE
Fix for videos freeze in chrome

### ISSUE THREAD

**Issue by rikial** [elementary/os#162]
Hi, i found a definitive fix without any throwbacks for this issue: [https://github.com/elementary/os/issues/121](https://github.com/elementary/os/issues/121), but the post has been restricted so i figured i could post it here.

It's sufficient to start chromium with the flag --disable-gpu-vsync and the problem completely goes away.

It's possible to make chromium start with this flag by default, just execute this command in the terminal, restart chrome and the issue will be gone forever:

`sudo sh -c 'echo "CHROMIUM_FLAGS=--disable-gpu-vsync" > /etc/chromium-browser/customizations/10-gpufix'`

Let everybody on that post know then delete this one.

**Comment by Djaler** [comment]
This isn't a fix. Just a workaround for Chromium. But not for other apps.

**Comment by rikial** [comment]
Oops, on both the intel powered machines i’ve installed elementary on
chromium was the only app which gave me this exact issue and this finally
fixed it.

Il giorno sab 22 dic 2018 alle 08:03 Kirill Romanov <
notifications@github.com> ha scritto:

**Comment by deseven** [comment]
This is not a Chrome/Chromium bug, same thing happens with Skype, VLC and other apps that use hardware acceleration. This [fix](https://github.com/elementary/os/issues/121#issuecomment-432652260) adds a huge cpu overload that makes video playback laggy on slower hardware.
  
For people coming from google or other sources - this issue is half a year old, there is no real fix and no one seems to be interested in working on one, unfortunately. I guess you can try adding [some bounty on it](https://www.bountysource.com/issues/64338934-videos-freeze-while-audio-continues-to-play-in-chrome-videos-etc).

**Comment by Davide95** [comment]
Have you tried to disable v-sync for the entire system? It's obviously just a temporary workaround, but it might work.

As @deseven pointed out before, please consider [adding some bounty on it](https://www.bountysource.com/issues/64338934-videos-freeze-while-audio-continues-to-play-in-chrome-videos-etc).

**Comment by davidmhewitt** [comment]
Closing as the linked issue is also closed.
