### ISSUE TITLE
elementary Juno 5.0 creates swapfile on BTRFS

### ISSUE THREAD

**Issue by lhorace** [elementary/os#188]
Hey devs,

https://btrfs.wiki.kernel.org/index.php/FAQ#Does_btrfs_support_swap_files.3F

> Currently no. Just making a file NOCOW does not help, swap file support relies on one function that btrfs intentionally does not implement due to potential corruptions. The swap implementation used to rely on some assumptions which may not hold in btrfs, like block numbers in the swap file while btrfs has a different block number mapping in case of multiple devices.

After installation, I was surprise to see the installer created swapfile on BTRFS? AFAIK, BTRFS has just recently recieve support in Linux Kernel 5.0? In the mean time, it's occupying space that isn't being used?

Regards

**Comment by lhorace** [comment]
You guys not going to work on this, no need for me to wait patiently

**Comment by cassidyjames** [comment]
@lhorace for what it's worth, just because someone does not immediately respond does not mean nobody is going to work on it. We're just currently working on other things. We're also working to switch away from the Ubiquity installer, so we'll need to figure out if this affects @elementary/installer and @pop-os-distinst as well.
