### ISSUE TITLE
Lenovo 130-15AST Touchpad Working

### ISSUE THREAD

**Issue by First-Time-User** [elementary/os#192]
Lenovo 130-15AST Touchpad Working.

**Comment by danrabbit** [comment]
Moving to "OS" since device drivers are outside the scope of System Settings

**Comment by peteruithoven** [comment]
Possibly related Ubuntu issues:
https://askubuntu.com/questions/1049787/lenovo-ideapad-330-touchpad-not-working
https://forums.lenovo.com/t5/Other-Linux-Discussions/Ideapad-320-touchpad-not-working-in-Ubuntu-any-version/td-p/3836105
https://ubuntuforums.org/showthread.php?t=2394494

(elementary OS is build on Ubuntu, so especially for drivers it's always smart to search what's known for Ubuntu)

**Comment by davidmhewitt** [comment]
We rely on Ubuntu for the kernel and its included drivers due to the excellent support and testing that Canonical provide. You can always try and update the kernel yourself manually, but your mileage may vary as to whether it works any better or worse.

It's probably that this was resolved in later versions of elementary OS with newer kernels. But I'm closing this as it's outside the scope of what we can do anything about.
