### ISSUE TITLE
latest kernel 

### ISSUE THREAD

**Issue by nazar2sfive** [elementary/os#290]
https://github.com/bkw777/mainline

i wish elementary give us option to choose the latest kernel instead of old ubuntu kernel.

**Comment by danrabbit** [comment]
I'm going to close this as "Out of scope" because maintaining a kernel is a huge amount of work. Canonical has an entire team that works on hardware enablement and kernel-level security. As an organization, elementary doesn't currently have the kind of dedicated man hours that would make it a responsible decision to provide our own kernel.

For the forseeable future, using the Ubuntu LTS kernel is the best way to ensure that our users get a known good kernel that's well maintained and quality controlled.
