### ISSUE TITLE
ubuntu-session present in installed 6.0 dailes

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#352]
Reproducible in 6.0-daily.20200509 ISO at least

**Comment by davidmhewitt** [comment]
Can you run a `apt-cache rdepends --installed ubuntu-session` so we can see what pulled it in?

**Comment by cassidyjames** [comment]
@davidmhewitt whoops, already uninstalled it here since it was pulling in GNOME Shell and friends. :sweat_smile:

**Comment by micahilbery** [comment]
When running that command on the 5/11 daily I get an output of:
```
ubuntu-session
Reverse Depends:
  |gnome-shell
  |gnome-shell
```

**Comment by davidmhewitt** [comment]
Interesting, so it's `gnome-shell` that pulled in `ubuntu-session`.

Can you run the same command for `gnome-shell`?

**Comment by micahilbery** [comment]
```
gnome-shell
Reverse Depends:
  yaru-theme-gnome-shell
  ubuntu-session
  libecal-2.0-1
 |network-manager-gnome
 |network-manager-gnome
 |libnotify4
  libmutter-6-0
  gsettings-desktop-schemas
  gnome-settings-daemon
  gnome-bluetooth
  gir1.2-gnomebluetooth-1.0
  gjs
  gir1.2-gnomedesktop-3.0
  gdm3
```

**Comment by davidmhewitt** [comment]
To be clear, mostly as a note to myself in the future. It hasn't been present in the ISO for a while, but distinst was installing after setup it due to some dependencies that it was resolving when cleaning up at the end.

I've just installed today's daily (20180813) and after installation GNOME/Ubuntu session is not installed and I think there's a reasonable chance the installation won't require an internet connection too (but I didn't test that).

I'll mark this as closed for now, fixed by https://github.com/elementary/pantheon-agent-polkit/pull/61
