### ISSUE TITLE
Laggy on Macbook Pro with Linux Kernel 5.x (generic)

### ISSUE THREAD

**Issue by triangulumlabs** [elementary/os#378]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug
I installed EOS (elementaryos-5.1-stable.20200603) on Macbook Pro 2013 and found out:
- GUI is very laggy.
- Characters show slowly long after keyboard is typed

I search on Google and found out that Linux Kernel 5.x doesn't work well on Macbook Pro. The same thing happened with Ubuntu >= 18.04.3 (With kernel 5.x), Kernel 4.18 works fine on Macbook Pro. So I tried with these following methods:
- Install linux-image-4.15 but when EOS is booted with kernel 4.15, keyboard and trackpad are not recognized. CAN EOS SUPPORT LINUX KERNEL 4.X ?
- Install linux-image-5.3-lowlatency, the GUI seems better, BUT wifi is not available

### To Reproduce
Open Apps and tried to interact as much as you can.

### Expected behavior

GUI is well, smoothly responding
## Platform Information

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

**Comment by hanaral** [comment]
Could you list the hardware your laptop has? I don't have such issues on my 2011 low end Air. You should't be switching kernels btw, since it can create a lot of issues with proprietary drivers that macbooks have (Broadcomm and Nvidia only provide release drivers, and since elementary uses LTS, you probably won't be able to use them with unsupported kernels)

**Comment by triangulumlabs** [comment]
Hi,
This is hardware specs of my Macbook
`00:00.0 Host bridge: Intel Corporation Crystal Well DRAM Controller (rev 08)
00:01.0 PCI bridge: Intel Corporation Crystal Well PCI Express x16 Controller (rev 08)
00:02.0 VGA compatible controller: Intel Corporation Crystal Well Integrated Graphics Controller (rev 08)
00:03.0 Audio device: Intel Corporation Crystal Well HD Audio Controller (rev 08)
00:14.0 USB controller: Intel Corporation 8 Series/C220 Series Chipset Family USB xHCI (rev 05)
00:16.0 Communication controller: Intel Corporation 8 Series/C220 Series Chipset Family MEI Controller #1 (rev 04)
00:1b.0 Audio device: Intel Corporation 8 Series/C220 Series Chipset High Definition Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #1 (rev d5)
00:1c.2 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #3 (rev d5)
00:1c.3 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #4 (rev d5)
00:1c.4 PCI bridge: Intel Corporation 8 Series/C220 Series Chipset Family PCI Express Root Port #5 (rev d5)
00:1f.0 ISA bridge: Intel Corporation HM87 Express LPC Controller (rev 05)
00:1f.3 SMBus: Intel Corporation 8 Series/C220 Series Chipset Family SMBus Controller (rev 05)
02:00.0 Network controller: Broadcom Limited BCM4360 802.11ac Wireless Network Adapter (rev 03)
03:00.0 Multimedia controller: Broadcom Limited 720p FaceTime HD Camera
04:00.0 SATA controller: Samsung Electronics Co Ltd Apple PCIe SSD (rev 01)
05:00.0 PCI bridge: Intel Corporation DSL5520 Thunderbolt 2 Bridge [Falcon Ridge 4C 2013]
06:00.0 PCI bridge: Intel Corporation DSL5520 Thunderbolt 2 Bridge [Falcon Ridge 4C 2013]
06:03.0 PCI bridge: Intel Corporation DSL5520 Thunderbolt 2 Bridge [Falcon Ridge 4C 2013]
06:04.0 PCI bridge: Intel Corporation DSL5520 Thunderbolt 2 Bridge [Falcon Ridge 4C 2013]
06:05.0 PCI bridge: Intel Corporation DSL5520 Thunderbolt 2 Bridge [Falcon Ridge 4C 2013]
06:06.0 PCI bridge: Intel Corporation DSL5520 Thunderbolt 2 Bridge [Falcon Ridge 4C 2013]
07:00.0 System peripheral: Intel Corporation DSL5520 Thunderbolt 2 NHI [Falcon Ridge 4C 2013]`

**Comment by martinstork** [comment]
If the same issues occur on 18.04 it's definitely a kernel issue that elementary practically can't resolve. If Ubuntu 20.04 seems to resolve your issues, you unfortunately have to wait for elementaryOS 6.0 (build on top of Ubuntu 20.04). Otherwise your unfortunately out of luck here. You might need to file a bug @ https://bugzilla.kernel.org

**Comment by davidmhewitt** [comment]
I'm going to close this as it definitely sounds like driver/kernel specific issues that we have no control over.

elementary ships Ubuntu kernels due to the excellent support and testing that Canonical provide for them. As always it's possible to manually install different versions yourself, but your mileage may vary with whether it works any better or worse.
