### ISSUE TITLE
Ethernet not supported on motherboard + solution

### ISSUE THREAD

**Issue by clausbertels** [elementary/os#420]
Hi guys

I have an issue but also a solution. I couldn't find the right repo for this. Apologies. Hopefully you guys can implement this.

**Problem**
No ethernet connection detected on Motherboard Gigabyte B550I Aorus Pro AX. 

**Solution**
1. Install r8125 driver from [here](https://www.realtek.com/en/component/zoo/category/network-interface-controllers-10-100-1000m-gigabit-ethernet-pci-express-software).
2. 
```
sudo touch /etc/NetworkManager/conf.d/10-globally-managed-devices.conf
sudo service network-manager restart
```

**Comment by davidmhewitt** [comment]
We use the kernels and drivers provided by Ubuntu due to the excellent support and testing that Canonical support.

We have no intention to manually ship 3rd party (possibly proprietary) drivers outside of what Ubuntu provide.

It's possible that a driver for this device would get included or is already included in newer kernels. You could have a look on the Ubuntu and linux kernel bug trackers to see if there's any requests for this driver to be included there.
