### ISSUE TITLE
Steam Doesn't work

### ISSUE THREAD

**Issue by Thai07** [elementary/os#479]
![Ekran_goruntusu_2021-05-07_09-20-52](https://user-images.githubusercontent.com/61286182/117460499-4040c680-af55-11eb-990a-596c5f853624.png)

**Comment by marbetschar** [comment]
You need to enable the i386 architecture repository in order to successfully install and use Steam on Ubuntu 20.04 LTS. In your Terminal execute:

```
$ sudo dpkg --add-architecture i386
$ sudo apt update
# now try to install steam again:
$ sudo apt install steam
```

Please note this is not an issue with elementary OS, its caused by its Ubuntu 20.04 LTS base. For further information, please see https://linuxconfig.org/how-to-install-steam-on-ubuntu-20-04-focal-fossa-linux
