### ISSUE TITLE
Mirrors stall out, slowing down ISO builds

### ISSUE THREAD

**Issue by cassidyjames** [elementary/os#509]
Something that is becoming a real annoying issue when building OS images locally is that the mirrors frequently stall out and sit for several minutes—whatever step is right after installing Flatpaks. Is there a way we can use the same mirror as in the config file for this step while ensuring it gets reset back to the mirrors URL for the actual installed image?

**Comment by davidmhewitt** [comment]
This has been annoying me today too. That's it configuring the mirrors sources in the actual image, so it has to use those. But it's to do with this:

https://github.com/elementary/os/blob/f8f0031a1a80129f2443f38c8acff1d117d67504/etc/auto/config#L37

I'm pretty sure it's set like that because we were getting some build failures in GitHub Actions related to something taking a long time to respond or occasionally having errors, but definitely worth reducing/removing those flags locally. We could experiment with reducing them for GH Actions too.
