### ISSUE TITLE
ISO of elementaryOS 6 stable does not work with Ventoy USB stick

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/os#544]
I put an elementary 6 stable ISO (20210810) next to my elementary stable 5.1 (20200814) ISO on my Ventoy USB Stick.

When selection the elementary OS 5.1 ISO in boot menu of ventoy, it loads correctly, when choosing the 6.0 ISO, it displays an error message: 

```
error: invalid magic number
error: you need to load the kernel first.

Press any key to continue ...
```

**Comment by cassidyjames** [comment]
Hm, we'll soon have a new ISO up on the homepage that you can try with, but otherwise I'm unsure of what would be causing this. Ventoy always seemed like magic to me. :smile:

**Comment by vjr** [comment]
What hardware do you have?

Can you try pressing `Ctrl + r ` in the ventoy boot menu iso list then it should show `GRUB2 Mode` in red letters after that can you select elementary 6 iso to see whether it boots?

**Comment by jeremypw** [comment]
I don't know if this issue is relevant at all? https://github.com/elementary/files/issues/1784

**Comment by davidmhewitt** [comment]
Are you 100% sure that the iso file was copied to the Ventoy USB correctly? Do the checksums of the file on the USB stick match the checksums of the file you downloaded?

I've just tried the latest stable iso and the latest version of Ventoy and it all worked as expected with no extra tweaks needed.

The only posts I find when Googling your error messages are people that solved the issue by re-copying the iso file to the USB stick because it had been corrupted somehow.

If you used Files to copy the iso, Jeremy's comment may be relevant.

**Comment by CodingSpiderFox** [comment]
I used Windows to create and copy the ISOs to the stick and I always wait about half a minute before I plug it out but I will overwrite the ISO and try again.

**Comment by diogopessoa** [comment]
I have elementary 6 and other ISOs on Ventoy and they all work fine.

But there are two details that I think it's important to note: 

* the first time you put the ISO on Ventoy, note that it takes a while to release the pendrive.
* In the BIOS boot priority setting, you must choose the exact pendrive name (ex: Sandisk).

**Comment by davidmhewitt** [comment]
I'm going to close this issue as we have 2 confirmations that it does work with Ventoy, so this isn't a problem with the elementary iso.
