### ISSUE TITLE
initrd.img not in gzip format

### ISSUE THREAD

**Issue by codygarver** [elementary/os#93]
Looks like Ubuntu changed something?
```
P: Begin installing disk information...

gzip: ../../binary/casper/initrd.img-4.15.0-23-generic: not in gzip format
cpio: premature end of archive
```

**Comment by codygarver** [comment]
`intel-microcode` is mutilating `initrd.img-*` so it doesn't contain `conf/uuid.conf` that casper needs. Gonna exclude `intel-microcode` from the live session somehow but preserve it for the installation.

**Comment by codygarver** [comment]
Fixed by elementary/os-patches@c516b4dfbe97138d08c03faa851b9298786880c8

**Comment by opensensesolutions** [comment]
I think maybe you ran into the same problem as me after an intel-microcode update, I was just using gunzip to extract it and it always worked but:
"It turns out the initrd generated by Debian's live-build (and to my surprise, accepted by the kernel) is actually the concatenation of two images:"

You can use the method described here to extract it even with the latest intel-microcode packages:
https://unix.stackexchange.com/questions/163346/why-is-it-that-my-initrd-only-has-one-directory-namely-kernel

Supposedly some of the intel-microcode patches are pretty important so you might want to include them when running live.

**Comment by codygarver** [comment]
The build failure and generic error message returned today. I see there have been changes in different packages that I looked at before to figure out the workaround, so that's where I will start.

**Comment by codygarver** [comment]
This was fixed upstream in `intel-microcode`:
```
intel-microcode (3.20180425.1~ubuntu0.18.04.2) bionic; urgency=medium

  * Default to early instead of auto, and install all of the microcode,
    not just the one matching the current CPU, if MODULES=most is set
    in the initramfs-tools config (LP: #1778738)

 -- Julian Andres Klode <juliank@ubuntu.com>  Tue, 26 Jun 2018 16:31:30 +0200
```

No need for workaround `disable-intel-microcode` anymore so it's been dropped from the iso.

**Comment by codygarver** [comment]
Or here:
```
live-build (3.0~a57-1ubuntu34.1) bionic; urgency=medium
  * ubuntu-initramfs-handling.patch: Use initramfs-tools to work with initrds,
    instead of trying to naively repack and unpack them blindly (LP: #1778811)
  * debian/control: Need to depend on initramfs-tools which isn't in chroots.
 -- Adam Conrad <adconrad@ubuntu.com>  Tue, 26 Jun 2018 16:36:32 -0600
```
